FROM node:8
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY pm2.json ./
RUN npm install
RUN npm install pm2 -g
CMD ["mkdir" ,"Almacen"]
# If you are building your code for production
# RUN npm install --only=production
COPY . .
EXPOSE 3000 22
# Show current folder structure in logs
# RUN ls -al -R
#CMD ["npm", "start"]
CMD ["pm2-runtime", "start", "pm2.json"]
