version: '3'
services:
   nginx:
      image: nginx:latest
      restart: always
      volumes:
        - /home/elecciones/recibido:/code
        - ./elecciones.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 0.0.0.0:80:80
      environment:
        - NGINX_HOST=elecciones.com
        - NGINX_PORT=80
